export const SET_REQUEST_STATUS = 'SET_REQUEST_STATUS';
export const RECEIVE_STOCKS = 'RECEIVE_STOCKS';
export const RECEIVE_SINGLE_STOCK = 'RECEIVE_SINGLE_STOCK';
export const SET_ERROR_STATUS = 'SET_ERROR_STATUS';
